config/routes.rb
PrinterShack::Application.routes.draw do
  get "tag/list"

  get "tag/show"

  get "forum/index"

  get "forum/reply"

  get "forum/show"

  get "forum/post"

  get "forum/create"

  get "catalog/index"

  get "catalog/show"

  get "catalog/search"

  get "catalog/latest"

  get "checkout/index"

  get "thank_you/place_order"

  get "checkout/thank_you"

  resources :line_items

  resources :carts

  get "users/new"

  get "pages/home"

  get "welcome/contact"

  get "welcome/about"

  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :products
  resources :users
  resources :sessions

  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

    root :to => "welcome", :action => "home"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
    has_many :line_items, :dependent => :destroy
def add_product(product)
    current_item = line_items.where(:product_id => product.id).first
if current_item
    current_item.quantity += 1
    else
    current_item = LineItem.new(:product_id => product.id)
    line_items << current_item
end
    current_item
end
    def total_price
    total = 0
    line_items.each do |line_item|
    total += line_item.product.price * line_item.quantity
    end
    total
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :initialize_cart
  # GET /carts
  # GET /carts.xml
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.xml
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cart }
    end
  end
  def your_cart
    redirect_to :action => "show", :id => current_cart.id
  end

  # GET /carts/new
  # GET /carts/new.xml
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.xml
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to(@cart, :notice => 'Cart was successfully created.') }
        format.xml  { render :xml => @cart, :status => :created, :location => @cart }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.xml
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to(@cart, :notice => 'Cart was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cart.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.xml
  def destroy
      @cart = Cart.find(params[:id])
      @cart.destroy
      session[:cart_id] = nil

      respond_to do |format|
        format.html { redirect_to(products_url, :notice =>'Your cart is currently empty') }
        format.xml { head :ok }
    end
  end
end

def add
@cart= Cart.find(params[:id])
if request.xhr?
@item = @cart.add(params[:id])
flash.now[:cart_notice] = "Added <em>#{@item.manufacturer.title}</em>"
render :action => "add_with_ajax"
elsif request.post?
@item = @cart.add(params[:id])
flash[:cart_notice] = "Added <em>#{@item.cart.title}</em>"
redirect_to session[:return_to] || {:controller => "catalog"}
else
render
end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_notice.html.erb
<p id="cart_notice"><%= flash[:cart_notice] %></p>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


        |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie, www.it247.ie
</div>

app/views/carts/_item.html.erb
<%= link_to item.cart, :action => "show",
:controller => "products", :id => item.manufacturer %>
<%= pluralize(item.amount, "pc", "pcs") %>,
$<%= sprintf("%0.2f", item.price * item.amount) %>

(<%= remove_cart_link("-", item.cart) %>)


app/views/carts/cart.html.erb
<% if flash[:cart_notice] %>
<%= render :partial => "cart/cart_notice" %>
<% end %>

<h3>Your Shopping Cart</h3>

<ul>
<% for item in @cart.cart_items %>
<li id="cart_item_<%= item.book.id %>">
<%= render :partial => "cart/item", :object => item %>
</li>
<% end %>
</ul>
<p id="cart_total"><strong>Total: $<%= sprintf("%0.2f", @cart.total) %> ➥
</strong></p>

        |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie, www.it247.ie
</div>


app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

        |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie, www.it247.ie
</div>

app/views/carts/index.html.erb
<h1>Checkout</h1>


<p><em>Your order is displayed in the shopping cart.</em></p>
    <form method="post" id="cart" action=>
    <fieldset>
    <legend>Contact Information</legend>

<p>
    <%= submit_tag "Place Order"%>
</p>

<p>
    <label for="order_email">Email</label><br/>
    <%= text_field :order, :email %>
<p>
    <label for="order_phone_number">Phone number</label><br/>
    <%= text_field :order, :phone_number %>
</p>


</fieldset>

</form>

<fieldset>
    <legend>Shipping Address</legend>
<p>
    <label for="order_ship_to_first_name">First name</label><br/>
    <%= text_field :order, :ship_to_first_name %>
</p>
<p>
    <label for="order_ship_to_last_name">Last name</label><br/>
    <%= text_field :order, :ship_to_last_name %>
</p>
<p>
    <label for="order_ship_to_address">Address</label><br/>
    <%= text_field :order, :ship_to_address %>
</p>
<p>
    <label for="order_ship_to_city">City</label><br/>
    <%= text_field :order, :ship_to_city %>
</p>
<p>
    <label for="order_ship_to_postal_code">Postal/Zip code</label><br/>
    <%= text_field :order, :ship_to_postal_code %>
</p>
<p>

   <label for="order_ship_to_postal_code">Country</label><br/>
    <%= text_field :order, :ship_to_country %>

</p>
</fieldset>

<fieldset>
    <legend>Billing Information</legend>
<p>
          <label for="order_card_type">Credit card type</label><br/>
    <select name="order[card_type]" id="order_card_type">
    <%= options_for_select([ "Visa", "MasterCard", "Discover" ]) %>
</select>
</p>
<p>
    <label for="order_card_expiration_month">Expiration date</label><br/>
    <select name="order[card_expiration_month]">
    <%= options_for_select(%w(1 2 3 4 5 6 7 8 9 10 11 12)) %>
</select>
/
    <select name="order[card_expiration_year]">
    <%= options_for_select(%w(2011 2012 2013 2014 2015 2016 2017 2018 2019 2020)) %>
</select>
</p>

<p>
    <label for="order_card_number">Card number</label><br/>
    <%= text_field :order, :card_number %>
</p>
<p>
    <label for="order_card_verification_value">
    <abbr title="Card Verification Value">CVV</abbr>/
    <abbr title="Card Validation Check">CVC</abbr>
</label><br/>
    <%= text_field :order, :card_verification_value %>

</p>
</fieldset>




    
</form>

        |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie, www.it247.ie
</div>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

       |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie, www.it247.ie
</div>

app/views/carts/place_order.html.erb
<h1>Checkout place_order</h1>
<p>Thank you for your order, do come back</p>

        |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie, www.it247.ie
</div>

app/views/carts/remove.html.erb
<strong>Please confirm removing one <em><%= @product.title %></em>
from your shopping cart.</strong>
<%= button_to "Confirm", :action => "remove", :id => params[:id] %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<% if flash[:cart_notice] %>
    <%= render :partial => "cart/cart_notice" %>
<% end %>

        <h2>Your Shopping Cart</h2>

<p>
        <strong>
        <%= link_to "Proceed to Checkout", :controller => 'checkout' unless controller.controller_name == 'checkout' %>
        </strong>
</p>
<ul>
    <% for item in @cart.line_items %>
        <li><%= item.quantity %> &times; <%= item.product.manufacturer %>     <%= item.product.price %>

        </li>

        <% end %> <br>
        Total Price: <%= number_to_currency(@cart.total_price, :unit => '&euro;') %><br/>
        <br/>
        <%= button_to 'Empty cart', @cart, :method => :delete, :confirm =>'Are you sure?' %>
</ul>

        |<%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

app/views/carts/thank_you.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Thank You</title>
</head>
<body>

For future references use invoice number <%= session[:order_id] %>

</body>
</html>