config/routes.rb
PrinterShack::Application.routes.draw do
  get "tag/list"

  get "tag/show"

  get "forum/index"

  get "forum/reply"

  get "forum/show"

  get "forum/post"

  get "forum/create"

  get "catalog/index"

  get "catalog/show"

  get "catalog/search"

  get "catalog/latest"

  get "checkout/index"

  get "thank_you/place_order"

  get "checkout/thank_you"

  resources :line_items

  resources :carts

  get "users/new"

  get "pages/home"

  get "welcome/contact"

  get "welcome/about"

  get "welcome/home"
  get "welcome/thank_you"
  get "welcome/register"

  resources :products
  resources :users
  resources :sessions

  match '/your_cart' => "carts#your_cart", :as => "your_cart"
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

    root :to => "welcome", :action => "home"

end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :user
    has_many :line_items

    attr_accessible :name, :description, :price

    def self.search(search_query)
      if search_query
        find(:all,:conditions => ['manufacturer LIKE ?', "%#{ search_query}%"])
      else
        find(:all)
      end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products
  # GET /products.xml
  def index
    @products = Product.search(params[:search_query])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @products }
      # Serve back JSON data example (use /products?format=json)
      format.json  { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.xml
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/new
  # GET /products/new.xml
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.xml
  def create
    @product = current_user.products.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to(@product, :notice => 'Product was successfully created.') }
        format.xml  { render :xml => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.xml
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(@product, :notice => 'Product was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.xml
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
def show_image (product)
    if product.image.nil?
      "No Image Stored"
    else
      img=image_tag(product.image.to_s, :align => "Product Image",:width=>"100", :height=>"100")
      link_to img, {:controller=>"products", :action=>"show", :id=>product.id}

    end
    end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :features %><br />
    <%= f.text_area :features %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<ul id="products">
<% for product in @products %>
<li class="product" id="product_<%= product.id %>">
<dl>
<dt><%= link_to product.title.t, :action => "show", :id => product %></dt>

<dd>Price: $<%= sprintf("%.2f", product.price) %></dd>

<strong>
<%= add_product_link("+", product) %>
</strong>
</dd>
</dl>
</li>
<%= draggable_element("product_#{product.id}", :revert => true) %>
<% end %>
</ul>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing products</h1>


<table>
  <tr>
    <th>Manufacturer</th>
    <th>Description</th>
    <th>Price</th>
    <th>Image</th>
    <th>Features</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.manufacturer %></td>
    <td><%= product.description %></td>
    <td><%= product.price %></td>
    <td><%= show_image (product) %></td>
    <td><%= product.features %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= button_to 'Add to Cart', line_items_path(:product_id => product) %></td>
  </tr>
<% end %>
</table>
<% form_tag products_path, :method => 'get' do %>
   <p>
<%= text_field_tag :search_query, params[:search_query] %>
     <%= submit_tag "Search", :name => nil %>
   </p>

<% end %>

<br />

        <%=link_to "Login Now", login_path%>
|       <%= link_to "Home", :controller => "welcome", :action => "home" %> |
        <%= link_to "Product Catalogue", products_path %> |
        <%= link_to "Register", :controller => "welcome", :action => "register" %> |
        <%= link_to "Login", login_path %>|
        <%= link_to "Logout", logout_path %> |
        <%= link_to "Your Cart", :controller => "carts", :action => "your_cart" %> |
        <%= link_to "Leave Site", :controller => "welcome", :action => "thank_you" %> |
        <%= link_to "Contact", :controller => "welcome", :action => "contact" %> |

<div id="footer">
&copy; 2011 Printer Shack. Designed by Torsby Attipoe - Phone: 0868407106, Email: info@it247.ie,
  <a href="http://www.IT247.ie/">Visit www.IT247.ie</a>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Manufacturer:</b>
  <%= @product.manufacturer %>
</p>

<p>
  <b>Description:</b>
  <%= sanitize(auto_link @product.description) %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Features:</b>
  <%= @product.features %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>